#!/bin/bash

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# SCP command to transfer the file to the user home directory
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ 

# Check if the SCP command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
else
    echo "Error transferring file. Check the parameters and try again."
fi
