#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Initialize a counter
counter=0

# Using an until loop to repeat the message until the counter reaches 10
until [ $counter -ge 10 ]; do
	echo "Best School"
	((counter++))
done
