#!/usr/bin/env bash
# This script displays messages based on loop iteration with superstitious numbers

# Initialize a counter
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
	# Using a case statement to display different messages
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac

	((counter++))
done
